controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes de notre application

# Controller: HomeController

# Appelle la page d'accueil
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|POST

 # Appelle la page static   

app_legal:
    path: /mentions
    controller: App\Controller\PageStaticController::mentionsLegales
    methods: GET

app_cookies:
    path: /cookies
    controller: App\Controller\PageStaticController::politiqueCookies
    methods: GET
#--------------------------
